### ISSUE TITLE
JMI and DISR generates the same score for selectable and non selectable case.

### ISSUE THREAD

**Issue by alecuba16** [Craigacp/FEAST#10]
Hello!

I'm testing the latest feast toolbox with this simple code:

> y=[zeros(5,1);ones(5,1)];
>
> X=ones(1,10); %Constant 
> X=[X' rand(10,1)]; %Random 
> X=[X y]; %Just a copy of target Y
>
> [sel,score]=feast('jmi',3,X,y)
> sel =
>     3
>     1
>     2
> 
> score =
>   1
>   1
>   1

And the score of all the variables are the same. Is that the desired result? I'm expecting different scores.

**Comment by Craigacp** [comment]
This is expected behaviour. Feature three has mutual information 1 with the target so is selected first. Feature 1 has zero mi with the target as it has zero entropy, but jmi's score criterion is sum_i I(X_i,X_j;Y), which is 1, and feature 2 has zero mi with the target, so also scores 1. The same is true for disr as it's just a normalized jmi.

**Comment by Craigacp** [comment]
The selection order is a function of the score. You shouldn't reorder the scores by the selected variables, they are returned in the correct order (i.e. score[0] is the score for the feature named in sel[0]).

**Comment by Craigacp** [comment]
I don't think adjusting the scores based on the other scores observed within an iteration is a good idea, it'll make the outputted scores look very strange.

**Comment by alecuba16** [comment]
Summarizing, there is no way to cut by some score or factor the number of features based on each iteration result.

You propose to use some third method in a closed loop to evaluate how much features are needed for a certain score.

The problem that I see with this is that it depends on the method needed.  In my case, each final iteration of my classifier algorithm takes almost a day. Is a very complex deep learning multilayer with multiple types (convolutional, lstm, dense...) layers to capture the patterns.  So I don't see the viability to implement in a closed loop with FS methods.

Do you have any suggestion of the third algorithm that might be used to evaluate the number of features? I checked the state of the art and is a very domain (data), dependant. I would expect a fully automatic feature selection without a human intervention, each time that a model is regenerated.

thanks for your advice.

**Comment by Craigacp** [comment]
You can implement something based on the scores provided by FEAST (e.g. we occasionally used mRMR but cut it at the point the score turned negative), but it would be specific to each feature selection algorithm, and not theoretically well grounded. Getting a full feature ordering then cutting it when the delta between two feature's scores is below some threshold will probably work, but for things like JMI and DISR where the score isn't monotonic there is no guarantee that it won't be above the threshold later. CMIM is monotonically decreasing and works better than mRMR so you could cut that at a specific threshold and guarantee that there are no unselected features with a higher score.

There is no fully automatic feature selection process, the best you'll get is a wrapper over features selected by a filter, or some kind of time penalty tradeoff. If you're in a linear space then things like Lasso work well and are as close as you'll get to something automatic, but for non-linear spaces the feature selection problem is NP-hard.

**Comment by alecuba16** [comment]
Thanks for your fast reply,

I'm working with data that is not linear; this is why I'm using deep learning. The dataset is coming from wind turbines where many different independent control systems determine the interaction of features with no relation between them. For instance, the temperatures between internal system and external radiator don't have even a linear zone. It is affected by others systems and control, so the dataset is very chaotic in terms of lack of correlations and linear relations between at least one feature.

I was trying to reduce the number of features to get a better-generalized model since now I'm suffering from overfitting. 

Ok, I will try with my data with CMIM, if the selection order of CMIM is correlated (negatively or positively) with the score is just what I need for a first approach. I will define the threshold of cut by the exploration of several results and with the human support knowledge in wind turbines.

The original issue is solved.

Once I get more time, I will explore other ways to define cut criteria depending on the method, maybe search for some well-found decision threshold.
