### ISSUE TITLE
Cannot find the referenced paper

### ISSUE THREAD

**Issue by AndreasGocht** [Craigacp/FEAST#11]
Hey,

I am looking for the following paper you mentioned:

```
 Information Theoretic Feature Selection for Cost-Sensitive Problems
 A. Pocock, N. Edakunni, M.-J. Zhao, M. Lujan, G. Brown.
 ArXiv
```

I didn't find it on ArXiv. Can you provide me a link?

Best,

Andreas

**Comment by Craigacp** [comment]
Unfortunately we didn't sort that out in time to go with the release, but a longer version of it is in chapter 7 of my PhD thesis - http://academic.adampocock.com/publications/pocockPhDThesis.pdf, page 135 onwards. I'll fix the reference.

**Comment by Craigacp** [comment]
References in the code and README are fixed.
