### ISSUE TITLE
Undefined function or variable 'FSToolbox

### ISSUE THREAD

**Issue by iNoufAlsubaie** [Craigacp/FEAST#13]
Hi, 

Am using Matlab and am facing an "Undefined function or variable 'FSToolbox'." error when I run 'testFSToolbox.m' file. 
Any advice please ?

Thank you

**Comment by Craigacp** [comment]
Ahh, that file was accidentally included when I rearranged the source directories. It was used for testing the FEAST implementations against the older single algorithm ones I wrote during my PhD, and isn't necessary. I've removed it from the source tree.

To use FEAST you need to have compiled it by running CompileFEAST, then the main feast and other matlab functions should work.
