### ISSUE TITLE
can you help to find something similar  in python 

### ISSUE THREAD

**Issue by Sandy4321** [Craigacp/FEAST#14]
can you help to find something similar  in python

**Comment by Craigacp** [comment]
There's a python API in progress in the `devel` branch. Other than that I think scikit-feature has many of the same algorithms implemented, though I think they are less optimized.

**Comment by Sandy4321** [comment]
When it will be ready?

**Comment by Craigacp** [comment]
Not sure, as I have to get permission to work on open source projects, even ones I've created. The CMIM and weighted CMIM implementations in the devel branch work just fine and you can just replace the word `CMIM` with `mRMR` or `JMI` to get working versions of those algorithms. The other ones in FEAST require slightly different arguments, but CMIM, mRMR and JMI are the best performing algorithms so there is little reason to use the others unless it's for comparison to write a paper on feature selection.

**Comment by Sandy4321** [comment]
great let me try
only how to find this devel branch project
is it here
https://github.com/Craigacp/FEAST/branches/all
??

**Comment by Sandy4321** [comment]
may be it is
https://github.com/Craigacp/FEAST/tree/devel/python
but how to install
do I need C++ compiler to install?
I do have Windows computer...

**Comment by Craigacp** [comment]
First clone the git repository, there are instructions on GitHub's help pages for how to do that. Then checkout the development branch with `git checkout develop`. Then run `python setup.py develop` or use your preferred python package installation tool (e.g. into a virtual environment or conda). It requires `make` and `gcc` to compile the C library that the python code uses. After that you should be able to use feast from python.
