### ISSUE TITLE
Mex file crash

### ISSUE THREAD

**Issue by chuong98** [Craigacp/FEAST#5]
Hi, I tried to use the Matlab toolbox, but I got crash with the mex file.
I attached the log file created by matlab. Thank you. 

------------------------------------------------------------------------
          Access violation detected at Sun Aug 07 20:39:05 2016
------------------------------------------------------------------------

Configuration:
  Crash Decoding      : Disabled
  Crash Mode          : continue (default)
  Current Graphics Driver: Unknown hardware 
  Default Encoding    : windows-1252
  Graphics card 1     : NVIDIA ( 0x10de ) NVIDIA GeForce GTX 560 Ti Version 9.18.13.4788
  Graphics card 2     : NVIDIA ( 0x10de ) NVIDIA Tesla M2090 Version 10.18.13.6256
  Host Name           : ChuongWin8
  MATLAB Architecture : win64
  MATLAB Root         : C:\Program Files\MATLAB\R2016a
  MATLAB Version      : 9.0.0.341360 (R2016a)
  OpenGL              : hardware
  Operating System    : Microsoft Windows 8.1 Pro
  Processor ID        : x86 Family 6 Model 45 Stepping 6, GenuineIntel
  Virtual Machine     : Java 1.7.0_60-b19 with Oracle Corporation Java HotSpot(TM) 64-Bit Server VM mixed mode
  Window System       : Version 6.3 (Build 9600)

Fault Count: 1

Abnormal termination:
Access violation

**Comment by chuong98** [comment]
[matlab_crash_dump.10728.txt](https://github.com/Craigacp/FEAST/files/405996/matlab_crash_dump.10728.txt)

**Comment by Craigacp** [comment]
What kind of data are you running FEAST with? How many values per feature, and how many labels?

Can you modify the compile scripts to add the "-g" flag to the mex lines (before all the source files) and rerun the computation and send that crash log.

**Comment by chuong98** [comment]
Hi, I recompiled the lib with the debug option.

mex -g -I../MIToolbox FSToolboxMex.c BetaGamma.c CMIM.c CondMI.c DISR.c ICAP.c JMI.c mRMR_D.c ../MIToolbox/MutualInformation.c ../MIToolbox/Entropy.c ../MIToolbox/CalculateProbability.c ../MIToolbox/ArrayOperations.c

Please find the attached files for the crash_log, and the data.
X0 is the feature matrix, which has 268 samples, each sample is a 150 dimension vector.
Y is the label vector (268 x1) which has value {1,2}. 
[Crash_logs_09_06_16_08_08_16.zip](https://github.com/Craigacp/FEAST/files/407110/Crash_logs_09_06_16_08_08_16.zip)
Thank you. 

[data_Train.zip](https://github.com/Craigacp/FEAST/files/407098/data_Train.zip)

**Comment by Craigacp** [comment]
Your features aren't discretised, so the results are undefined. In this case FEAST applied a simple transform to create int values, which resulted in a very large range. Then when FEAST merged two arrays to use JMI it tried to allocate too much memory and crashed. You should discretise your data into around 10 bins before running FEAST.

**Comment by chuong98** [comment]
Oh, I see. Thank you for clarification.
