### ISSUE TITLE
Feature Score For CMIM

### ISSUE THREAD

**Issue by 13641362** [Craigacp/FEAST#6]
Dear Adam

I  need to get a score for each fearure as I need to to know the difference between them.  For example, how much important is feature 1 than feature 2?

Can please provide the code for that?

Thanks

Elina

**Comment by Craigacp** [comment]
Hi Elina,

You can use this [gist](https://gist.github.com/Craigacp/a4c3b09aeca7062736ba798ddecf7e53) for the time being. I'll eventually add this functionality to FEAST, but I won't have the time for at least a month.

Please check that it gives the same selected features on your data as FEAST does, the Matlab implementations of the algorithms I wrote as demos for MIToolbox are old and don't handle edge cases as well as the C ones in FEAST.

Adam

**Comment by 13641362** [comment]
Hi Adam,
I have tested this for the  top  12 features and  I got the eleven features the same but the  last one  is different.  What is your suggestion?

**Comment by Craigacp** [comment]
What index is the 12th selected feature in both versions? Also how many features are there in the dataset, and what score is reported by the MATLAB code for the 12th feature?

**Comment by 13641362** [comment]
Hi Adam,

I run the experiment again. The second top  feature is different this time. I have 813 features in total.  The scores and indexes are as follow.

Scores	CMIM_Code	Feast
0.013256	   393	       393
0.011089	   605	      555
0.007871	   475	    475
0.007003     370	   370
0.006021	   337	  337
0.004994	   432	  432
0.004892	   733	 733
0.004426	   450	 450
0.004316	   571	 571
0.004208	   572	 572
0.004062	     45	 45
0.003914	   535	535
0.003725	   206	206

**Comment by Craigacp** [comment]
For CMIM the min value is 0, and the maximum value is the minimum of H(Y) and H(X) for each feature, though to normalise them you can just divide everything by H(Y) and that will give you a value between 0 and 1.

**Comment by 13641362** [comment]
Hi Adam,

I dont do different run. It is only one run.  These results are for top 13 features out of 831. First and second column are MATLAB codes and the third column is Feast results. For example the second top feature is index 605 with MATLAB and 555 by feast! Please let me know, if it is clear?

**Comment by Craigacp** [comment]
The two features (605 and 555) are either identical or have the same conditional mutual information values. Given the rest of the features are selected in the same way I'd guess they are identical.

If you modify the gist by replacing the ">=" with ">" on lines 37 and 44, you should get the same answers out of FEAST and the MATLAB code. All that happens is the gist looks for the last feature with the highest value and FEAST looks for the first feature with the highest value, and this change switches the gist so it behaves like FEAST. There are still edge cases where they will return different results, but those are more complicated to fix.

**Comment by 13641362** [comment]
Thanks Adam,

I will do that and let you know.
Can we get these scores for JMI and Mrmr as well?

**Comment by Craigacp** [comment]
I'm currently working on a version of FEAST that has scores, if you check out the devel branch of this repo and recompile everything you should be able to use it. It's not quite finished yet, so please report any issues you have.

This provides scores for JMI and mRMR, but the JMI score is not monotonically decreasing as you select more features. The returned values are the totals of the criteria but in JMI's case this means it gives the total joint mutual information between the selected feature and all previously selected features. If you divide this by it's position in the list then you'll get something closer to being a score, but it's still not monotonically decreasing (and it's impossible to get such a score with JMI due to the way it's designed).

**Comment by Craigacp** [comment]
Feature scores for all algorithms have been added in FEAST v2.
