### ISSUE TITLE
segmentation fault

### ISSUE THREAD

**Issue by michelle171** [Craigacp/FEAST#7]
I compiled this code to use with PyFeast. I ran make x64 and sudo make install. When I tried to run the code that uses FEAST through PyFeast I got a segmentation fault. I determined the segmentation fault was due to the FEAST code. 

I didn't find instructions on proper installation with the make file, could the segmentation fault be due to incorrect installation, or are there any suggestions for another reason I got a segmentation fault?

**Comment by Craigacp** [comment]
PyFeast hasn't been updated to use the new API from FEAST v2. It only works with the v1 API. Which version of FEAST did you compile?

**Comment by michelle171** [comment]
I would've compiled the FEAST v2, can I access v1 using the makefile?

**Comment by michelle171** [comment]
I would've compiled v2, can I access v1 through the makefile? Thanks!

**Comment by michelle171** [comment]
What version of MIToolbox is required for v1?

**Comment by Craigacp** [comment]
The required MIToolbox is 2.1.2. I'd use FEAST v1.1.4, i.e. the last release before v2.

**Comment by Craigacp** [comment]
Did this fix the issue?

**Comment by michelle171** [comment]
Yes, I had to change the name of the MIToolbox-2.1.2 directory to MIToolbox without the version numbers for the FEAST program to recognize it. But after that it was working fine. Thank you for your help.

**Comment by Craigacp** [comment]
Ok.
